package com.swasthai.app.feature.citizen.records

import android.content.Context
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import com.swasthai.app.domain.model.ScreeningDetail
import com.swasthai.app.domain.model.ScreeningType
import com.swasthai.app.domain.model.Vitals
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Formats a generated report can be saved / shared as.
 */
enum class ReportFormat(
    val label: String,
    val extension: String,
    val mimeType: String
) {
    PDF("PDF", "pdf", "application/pdf"),
    IMAGE("Image", "png", "image/png"),
    TEXT("Text", "txt", "text/plain")
}

/**
 * Renders a real report from the stored [ScreeningDetail] — the actual
 * symptoms, vitals, prediction, risk and recommendations — into a file the
 * user can share or save. Nothing here is fake placeholder text.
 */
object ReportGenerator {

    /** Builds the full human-readable report content from real screening data. */
    fun buildLines(detail: ScreeningDetail, patientName: String): List<String> {
        val lines = mutableListOf<String>()
        val d = detail.screening
        val diagnosis = detail.diagnosis
        val date = SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault())
            .format(Date(d.createdAt))

        lines += listOf(
            "SWASTHAI HEALTH SCREENING REPORT",
            "=================================",
            "",
            "Patient name : ${patientName.ifBlank { "—" }}",
            "Screening    : ${when (d.screeningType) {
                ScreeningType.SYMPTOM_CHECK -> "Symptom Check"
                ScreeningType.VOICE_ASSISTANT -> "Voice Screening"
                ScreeningType.IMAGE_CHECK -> "Image Screening"
                ScreeningType.COMBINED -> "Combined Screening"
            }}",
            "Date         : $date",
            "Screening ID : ${d.id}"
        )

        if (diagnosis != null) {
            lines += listOf(
                "",
                "--- ASSESSMENT ---",
                "Likely condition : ${diagnosis.predictedDisease}",
                "Risk level       : ${diagnosis.riskLevel.name.lowercase().replaceFirstChar { it.uppercase() }}",
                "Confidence       : ${diagnosis.confidenceScore.toInt()}%"
            )
            if (diagnosis.differentialDiagnosis.isNotEmpty()) {
                lines += "Other possibilities: ${diagnosis.differentialDiagnosis.joinToString(", ")}"
            }
        }

        if (detail.symptoms.isNotEmpty()) {
            lines += listOf("", "--- REPORTED SYMPTOMS ---")
            detail.symptoms.forEach { s ->
                val duration = if (s.duration.isNullOrBlank()) "" else " (${s.duration})"
                lines += "• ${s.name}$duration"
            }
        }

        detail.vitals?.let { v ->
            lines += listOf("", "--- VITALS ---")
            v.temperature?.let { lines += "• Temperature      : %.1f °C".format(it) }
            v.pulse?.let { lines += "• Pulse            : $it bpm" }
            v.spo2?.let { lines += "• SpO2             : %.0f %%".format(it) }
            v.bloodPressure?.let { lines += "• Blood pressure   : $it mmHg" }
            v.weight?.let { lines += "• Weight           : %.1f kg".format(it) }
            v.height?.let { lines += "• Height           : %.1f cm".format(it) }
        }

        if (diagnosis?.medicalAdvice != null) {
            val advice = diagnosis.medicalAdvice!!
            lines += listOf(
                "",
                "--- AI DOCTOR EXPLAINS ---",
                "Why it happens   : ${advice.cause}",
                "What to do       : ${advice.remedy}",
                "Doctor to consult: ${advice.doctorToConsult}"
            )
            if (advice.urgencyHint.isNotBlank()) {
                lines += "Watch for        : ${advice.urgencyHint}"
            }
        }

        if (diagnosis != null && diagnosis.recommendations.isNotEmpty()) {
            lines += listOf("", "--- RECOMMENDATIONS ---")
            diagnosis.recommendations.sortedBy { it.priority }.forEach { r ->
                lines += "• ${r.text}"
            }
        }

        lines += listOf(
            "",
            "This report is generated by the on-device SwasthAI screening tool.",
            "It is a health suggestion and does not replace a doctor's diagnosis.",
            "Please consult a qualified health professional for medical advice."
        )
        return lines
    }

    fun generate(
        context: Context,
        detail: ScreeningDetail,
        patientName: String,
        format: ReportFormat
    ): Result<File> = runCatching {
        val dir = File(context.cacheDir, "reports").apply { mkdirs() }
        val file = File(dir, "SwasthAI_Report_${detail.screening.id}.${format.extension}")
        val lines = buildLines(detail, patientName)
        when (format) {
            ReportFormat.TEXT -> writeText(file, lines)
            ReportFormat.PDF -> writePdf(file, lines)
            ReportFormat.IMAGE -> writeImage(file, lines)
        }
        file
    }

    private fun writeText(file: File, lines: List<String>) {
        file.writeText(lines.joinToString("\n"))
    }

    private fun writePdf(file: File, lines: List<String>) {
        val document = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create()
        val page = document.startPage(pageInfo)
        val canvas = page.canvas
        val paint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = Color.BLACK
            textSize = 11f
        }
        val titlePaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = Color.rgb(0, 105, 92)
            textSize = 16f
            typeface = Typeface.DEFAULT_BOLD
        }
        var y = 48f
        // Title at top, then the content (skipping the text-only header block).
        canvas.drawText("SwasthAI Health Screening Report", 40f, y, titlePaint)
        y += 20f
        canvas.drawLine(40f, y, 555f, y, Paint().apply {
            color = Color.rgb(0, 105, 92)
            strokeWidth = 2f
        })
        y += 16f

        for (line in lines.drop(2)) {
            if (y > 800f) {
                document.finishPage(page)
                // overflow: keep first page only and stop whitespace runaway.
                break
            }
            for (segment in wrap(line, 470f, paint)) {
                if (y > 800f) break
                canvas.drawText(segment, 40f, y, paint)
                y += (paint.textSize * 1.35f)
            }
        }
        document.finishPage(page)
        FileOutputStream(file).use { output ->
            document.writeTo(output)
        }
        document.close()
    }

    private fun writeImage(file: File, lines: List<String>) {
        val width = 1080
        val height = 1920
        val bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
        val canvas = Canvas(bitmap)
        canvas.drawColor(Color.WHITE)

        val titlePaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = Color.rgb(0, 105, 92)
            textSize = 44f
            typeface = Typeface.DEFAULT_BOLD
        }
        val paint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = Color.rgb(33, 33, 33)
            textSize = 34f
        }
        var y = 110f
        canvas.drawText("SwasthAI Health Screening Report", 60f, y, titlePaint)
        y += 80f

        for (line in lines.drop(2)) {
            if (y > height - 60f) break
            for (segment in wrap(line, width - 120f, paint)) {
                if (y > height - 60f) break
                canvas.drawText(segment, 60f, y, paint)
                y += paint.textSize * 1.4f
            }
        }

        FileOutputStream(file).use { output ->
            bitmap.compress(Bitmap.CompressFormat.PNG, 95, output)
        }
        bitmap.recycle()
    }

    /** Basic word wrapping shared by the PDF and bitmap renderers. */
    private fun wrap(line: String, maxWidth: Float, paint: Paint): List<String> {
        if (line.isEmpty()) return listOf("")
        if (paint.measureText(line) <= maxWidth) return listOf(line)
        val words = line.split(" ")
        val result = mutableListOf<String>()
        val current = StringBuilder()
        for (word in words) {
            val candidate = if (current.isEmpty()) word else "$current $word"
            if (paint.measureText(candidate) <= maxWidth || current.isEmpty()) {
                current.append(if (current.isEmpty()) word else " $word")
            } else {
                result += current.toString()
                current.clear()
                current.append(word)
            }
        }
        if (current.isNotEmpty()) result += current.toString()
        return result
    }
}